### PR TITLE
[WIP] Support for Ecto 2.0

### PR DESCRIPTION
**Pull request by ankhers**
Just copying the list from #84
- [x] basic connection
- [x] loaders/dumpers
- [x] date/time loaders/dumpers
- [ ] query translator
- [x] insert
- [x] update
- [x] delete
- [x] insert_all
- [x] logging
- [ ] documentation

This is a list of the remaining tests that need to pass before the Ecto 2.0 cut can be made.

- [ ] test/mongo_ecto_test.exs:26

This is a list of tests that will not be fixed and why.

* deps/ecto/integration_test/cases/repo.exs:68 - Mongo does not officially support composite keys.
* deps/ecto/integration_test/cases/repo.exs:91 - Mongo does not officially support composite keys.
* deps/ecto/integration_test/cases/repo.exs:281 - Mongo does not support joins.
* deps/ecto/integration_test/cases/repo.exs:306 - Mongo does not support joins.
* deps/ecto/integration_test/cases/repo.exs:557 - Mongo does not support sub queries.
* deps/ecto/integration_test/cases/repo.exs:585 - Mongo considers `null` (or no value) to be the same across a unique index.
* deps/ecto/integration_test/cases/repo.exs:625 - Mongo considers `null` (or no value) to be the same across a unique index.
 * deps/ecto/integration_test/cases/repo.exs:890 - The [mongodb](https://github.com/ericmj/mongodb) package is making an explicit decision to only return string keys. I'm going to follow this because of the lack of schema associated with Mongo.
* deps/ecto/integration_test/cases/preload.exs:80 - Mongo does not support joins.
* deps/ecto/integration_test/cases/preload.exs:199 - Mongo does not support joins.
* deps/ecto/integration_test/cases/preload.exs:267 - Mongo does not support joins.
* deps/ecto/integration_test/cases/preload.exs:410 - Mongo does not seem to support true transactions.
* deps/ecto/integration_test/cases/preload.exs:483 - Mongo does not seem to support true transactions.
* deps/ecto/integration_test/cases/type.exs:64 - Mongo does cannot cast types in a query.
* deps/ecto/integration_test/cases/type.exs:86 - Mongo does cannot cast types in a query.
* deps/ecto/integration_test/cases/type.exs:94 - `^"a" in ^["a", "b", "c"]` does not translate well into Mongo.

### CODE REVIEW

**Comment by ankhers** [comment]
For anyone that is following along, I have to make a couple changes in the `mongodb` package that will make development on this adapter be a little smoother.

**Comment by hartator** [comment]
Awesome! Do you need more help? Seems there still are a lot to do.

**Comment by ankhers** [comment]
I would appreciate any help you or anyone else could provide. I currently
have a couple commits that I have not yet pushed. I should be able to push
them within an hour or two.

After that, just try and leave a message here with what you are working on
to try and prevent duplicate efforts.

**Comment by hartator** [comment]
Sure, will be glad to find sometime to help.

**Comment by cjbell** [comment]
@ankhers I'm very happy to take logging as I just ran into an issue with it and started to fix!

**Comment by scottmessinger** [comment]
@cjbell That would be awesome! I also ran into the logging issue today.

**Comment by cjbell** [comment]
@scottmessinger if you need something working right now, you can point to this branch (which is a fork of @ankhers `ecto-2` branch): https://github.com/madebymany/mongodb_ecto/tree/ecto-2-log-fix

**Comment by ankhers** [comment]
You can also configure your repository with `log: false` to prevent logging. Which is what I am using in a project at the moment. But I would appreciate an actual fix.

**Comment by AlexKovalevych** [comment]
Is this still alive? Sorry for bothering, but any idea when it would be possible to use ecto2 with mongo?

**Comment by ankhers** [comment]
I have not been actively working on this at the moment. I have gotten it to a point where it works enough for the project that I needed it for.

With that being said, I may need it working 100% in the near future, so I am trying to find a bit of time in order to fix up the remaining issues. Unfortunately, I do not have an ETA for completion.

**Comment by iStefo** [comment]
@ankhers: I absolutely understand that you may not find the time to continue updating this for Ecto 2.0 compat., and that is more than ok. Maybe you could describe what features/fixes are still missing, where to pick up your work and what resources you used to update the library.

On the other hand, describing what currently works in your branch could help others (like me) to decide whether it's already good enough for them, too.

**Comment by ankhers** [comment]
So after looking at the state of things, it appears that latest ecto master currently has a couple breaking changes. Which is not very surprising considering it appears to be targeting a 2.1.0 release.

I went from ~23 failing tests to 127 failing tests once I updated to the latest master. So I would not suggest using my branch in its current state as it will probably not work for most things. 

I haven't taken an in-depth look at what the changes are, but I am hoping that they will be relatively easy to fix. I should be able to find some time throughout the weekend in order to attempt to fix up some of the changes.

With that said, if you are currently looking to test whether or not it will work in a project you are working on and you are okay with being pinned to ecto v2.0.x, feel free to use my fork, but make sure you pin it to commit b3d1bba6326662bc4148d769eda19cf4734658d6. I can't guarantee that things work after that.

On my fork at that commit, most simple operations work. You should have no problems doing inserts, updates, deletes. However there were a couple failing tests in querying the database for certain information. I don't think aggregates are working at the moment.

If anyone would like to help with the current state of attempting to get this updated for ecto 2.1.0, feel free to fork my repo and just run the tests. Once all of the tests pass, the adapter should _hopefully_ be ready to be released proper.

If anyone does decide that they want to help out with some code, I would appreciate it if you put up an early PR in my repository to let everyone else know that something is being worked on and can either collaborate, or move onto another issue.

I know I didn't really go into detail about what parts of the adapter are working and which are not, but hopefully it gives you some idea of where this is standing @iStefo.

**Comment by cjbell** [comment]
Thanks @ankhers for the in-depth update. 

I also tried the Ecto 2.1.x branch recently with your mongodb_ecto fork. Looks like a lot of the changes come in from `insert/5` becoming `insert/6` to accommodate upserts. (See this commit in Ecto from the MySQL adapter for a reference: https://github.com/elixir-ecto/ecto/commit/1a9cb3bae5cbf59a6503e30df1a58e0b198fcc63)

We're actually running your fork in production right now (on Ecto 2.0.x) and aren't having any problems with the basic functionality (selects, updates, inserts, deletes). Seems like some of the JS querying stuff doesn't work, but we didn't use that anyway.

**Comment by ericmj** [comment]
I have released a new version 0.2.0 of the mongodb driver. There are no breaking changes from the db_conn branch you are using so it should be safe to switch over to fetching the driver from hex.

**Comment by Morganjackson** [comment]
@ankhers great job on this so far!

Do you think there is much left to do before it can be merged? 

I'm happy to kick in $200 if it helps at all?

**Comment by ankhers** [comment]
@Morganjackson Unfortunately I was unable to get much done on this over the weekend because of other obligations. I still do not know the full extent of what has changed in order to start fixing it. I should be able to find some time before the weekend to at least start looking at the changes.

As for the money, I appreciate the offer, but I am not really comfortable accepting money for working on a project that is not mine.

**Comment by ankhers** [comment]
Alright, slight update.

After speaking with @cjbell, I have decided to push for an ecto 2.0 compatibility release before ecto 2.1. So this branch is about to be reverted to the last known working state for ecto 2.0, while I have a separate `ecto-2.1` branch in my repository that has the few additional changes I have made for 2.1.

Hopefully this will not take too long. But at the very least there should be a stable release semi-shortly. I am currently counting 27 failing tests. I know for a fact that 4 of them are not actual failures, but I did not get my changes merged into upstream ecto before they updated their versions. So it is closer to 23 failing tests.

**Comment by gustavovnicius** [comment]
@ankhers I'm really needing mongodb_ecto support for Ecto 2.0, is there anything that I can do to help?

**Comment by ankhers** [comment]
@gustavovnicius Fork my repo -> switch to `ecto-2` branch -> run the tests -> pick one to fix -> send me a PR.

Just as a note though, I'm not planning on fixing the tests about joins or composite keys.

**Comment by ankhers** [comment]
For anyone that is following along with the (lack of) work being done on this PR, I was slightly side tracked and needed to implement SSL connections for the underlying mongo driver. ericmj/mongodb#95. I am am also hoping to get ericmj/mongodb#93 (replica sets) pushed through before doing more work on this.

**Comment by AlexKovalevych** [comment]
Getting error while running `mix ecto.reset`:

```
21:34:27.235 [error] GenServer #PID<0.1276.0> terminating
** (stop) exited in: GenServer.call(Mongo.Monitor, {:add_conn, #PID<0.1276.0>, nil, 4}, 5000)
    ** (EXIT) no process
    (elixir) lib/gen_server.ex:596: GenServer.call/3
    lib/mongo/protocol.ex:34: Mongo.Protocol.connect/2
    lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Mongo.Protocol
```

Have no error when i start the server. My dependencies:

```elixir
  defp deps do
    [{:phoenix, "~> 1.2.1"},
     {:phoenix_ecto, "~> 3.2.1"},
     {:phoenix_html, "~> 2.9.1"},
     {:phoenix_live_reload, "~> 1.0.6", only: :dev},
     {:mongodb_ecto, github: "ankhers/mongodb_ecto", branch: "ecto-2"},
     {:guardian_db, "~> 0.7.0"},
     {:ueberauth, "~> 0.4.0"},
     {:gettext, "~> 0.13"},
     {:ecto, "~> 2.0.6", override: true},
     {:cowboy, "~> 1.0"},
     {:comeonin, "~> 3.0"},
     {:ex_machina, "~> 1.0", only: [:dev, :test]}]
  end
```

Should i use different versions, or maybe i missed something here, how does it work for you?

**Comment by ankhers** [comment]
@AlexKovalevych Can you tell me the exact commands your `ecto.reset` alias is running?

**Comment by AlexKovalevych** [comment]
@ankhers It fails on `mix ecto.drop`. I guess, not a big deal, i can clean db manually, but it would be nice to have it out of the box.

**Comment by ankhers** [comment]
Indeed it does. I'm getting a slightly different error when using `mix ecto.drop`. I will look into this a bit more when I have some time.

**Comment by AlexKovalevych** [comment]
@ankhers here is a hot fix, not sure if its the best, but it works for me and not breaking tests https://github.com/ankhers/mongodb_ecto/pull/5

**Comment by AlexKovalevych** [comment]
@ankhers Do you have an idea how to run `aggregation` query in your fork? `Mongo.aggregate` expects `conn` as a first argument, how do i get it? Before it worked like `Mongo.aggregate(App.Repo. __mongo_pool__, ...)`, not i have `App.Repo.__pool__`, but it doesnt work: 

```
17:23:55.114 [error] Task #PID<0.2520.0> started from #PID<0.2519.0> terminating
** (MatchError) no match of right hand side value: []
    (mongodb) lib/mongo/monitor.ex:16: Mongo.Monitor.wire_version/1
    (mongodb) lib/mongo.ex:142: Mongo.aggregate/4
```

**Comment by AlexKovalevych** [comment]
@ankhers never mind, i figured it out. This one works:

```
    {pool, _} = App.Repo.__pool__
    Mongo.aggregate(pool, ...)
```

**Comment by ankhers** [comment]
This is just a list for anyone that is helping of which tests I do not plan on fixing and why.

* deps/ecto/integration_test/cases/repo.exs:281 - Mongo does not support joins.
* deps/ecto/integration_test/cases/repo.exs:306 - Mongo does not support joins.
* deps/ecto/integration_test/cases/preload.exs:80 - Mongo does not support joins.
* deps/ecto/integration_test/cases/preload.exs:199 - Mongo does not support joins.
* deps/ecto/integration_test/cases/preload.exs:267 - Mongo does not support joins.
* deps/ecto/integration_test/cases/repo.exs:68 - Mongo does not officially support composite keys.
* deps/ecto/integration_test/cases/repo.exs:91 - Mongo does not officially support composite keys.
* deps/ecto/integration_test/cases/repo.exs:585 - Mongo considers `null` (or no value) to be the same across a unique index, so there is no way of making this test pass.
* deps/ecto/integration_test/cases/type.exs:94 - `^"a" in ^["a", "b", "c"]` does not translate well into Mongo.

There are currently 17 test failures. There are 9 tests that will not be fixed. Which means there are only another 8 tests that should be fixed. However, maybe there should be a couple more tests to be written to cover any assertions in the skipped tests that may make sense.

**Comment by justmark** [comment]
Hi

Just started using this branch.  I've just started looking at Phoenix as a replacement for a Rails project (uses Mongoid) that I have up and running.

I put together a sample page to test some performance metrics against our Rails system (your module was blowing away speed metrics on Ruby/Mongoid, by the way) but I ran into an issue that seems to be related to the number of documents in a collection.

I had created a cursor for all the documents in a collection with:

```
systems = T4.Repo.all(Systems)
```

Passing this to a template, and paginated table worked great.  This small collection had ~180 documents.

I created a second database with roughly ~1500 documents and ran into an issue.  The query looks like  it ran fine, but an error then was posted to the logs:

```
[debug] Processing by T4.PageController.index/2
  Parameters: %{}
  Pipelines: [:browser]
[debug] QUERY OK db=18.1ms decode=7.4ms
FIND coll="systems" query=[{"$query", []}, {"$orderby", %{}}] projection=%{_id: true, cb_nickname: true, customerID: true, nickname: true, systemID: true, tz: true} []
[info] Sent 500 in 149ms
[error] #PID<0.352.0> running T4.Endpoint terminated
Server: my-hostname:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Mongo.Ecto.Connection.format_query/2
        (mongodb_ecto) lib/mongo_ecto/connection.ex:192: Mongo.Ecto.Connection.format_query(%Mongo.Query{action: :kill_cursors, extra: [375256676454]}, [])
        (mongodb_ecto) lib/mongo_ecto/connection.ex:167: Mongo.Ecto.Connection.log/3
        (db_connection) lib/db_connection.ex:1177: DBConnection.log/6
        (mongodb) lib/mongo.ex:386: Mongo.kill_cursors/3
        (elixir) lib/stream.ex:1263: Stream.do_resource/5
        (elixir) lib/enum.ex:1767: Enum.map_reduce/3
        (mongodb_ecto) lib/mongo_ecto.ex:531: Mongo.Ecto.execute/6
        (ecto) lib/ecto/repo/queryable.ex:127: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:40: Ecto.Repo.Queryable.all/4
        (t4) web/controllers/page_controller.ex:7: T4.PageController.index/2
        (t4) web/controllers/page_controller.ex:1: T4.PageController.action/2
        (t4) web/controllers/page_controller.ex:1: T4.PageController.phoenix_controller_pipeline/2
        (t4) lib/t4/endpoint.ex:1: T4.Endpoint.instrument/4
        (t4) lib/phoenix/router.ex:261: T4.Router.dispatch/2
        (t4) web/router.ex:1: T4.Router.do_call/2
        (t4) lib/t4/endpoint.ex:1: T4.Endpoint.phoenix_pipeline/1
        (t4) lib/plug/debugger.ex:123: T4.Endpoint."call (overridable 3)"/2
        (t4) lib/t4/endpoint.ex:1: T4.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

With our Rails installation, I could just iterate over the cursor to view results.  Is this handled differently through this module, or is perhaps something else wrong?

Thanks!

**Comment by ankhers** [comment]
@justmark 

According to your trace, it looks like it is an issue with logging. However, I want to dig down a bit deeper to make sure that we are not passing faulty data to that logging function. To get around this temporarily to keep testing, you can add `log: false` to your Repo config.

Unfortunately, this will no longer show you the time it took in the database. But you should still get an idea of how it performs while someone looks into a fix.

**Comment by justmark** [comment]
@ankhers

Thanks for the super quick response!  I added in the log: false, and that did the trick.  The error isn't reported, and all the data passed through to the table as I had hoped (very quickly, too.)

**Comment by AlexKovalevych** [comment]
@justmark in case you need logging, you can check this PR, which works for me: https://github.com/ankhers/mongodb_ecto/pull/8

**Comment by justmark** [comment]
@AlexKovalevych Thanks - I'll give that a shot too.  Thanks for the reply, its much appreciated.

**Comment by ankhers** [comment]
Just as a quick update to everyone, it appears that the only remaining test to fix is the JavaScript test.

If someone has any argument(s) for fixing the tests that I have decided to not fix (you can see the entire list in the PR description) please let me know. If you change my mind, or provide a PR, I will gladly attempt to fix it.

**Comment by michalmuskala** [comment]
That's an awesome news. I'll review the code over this week (or weekend).

I'll also do appropriate changes to ecto to make it possible to isolate the tests that require features MongoDB does not provide.

**Comment by ankhers** [comment]
As it turns out, I'm not entirely sure about making the javascript test pass. `where/2` requires a keyword list, and you cannot introduce keywords without making changes to ecto proper.

Is this something that people are even interested in using?

**Comment by scottmessinger** [comment]
@ankhers I never use javascript in my mongo queries as it can't make use of any indexes, so for me, the lack of `where/2` isn't a big deal at all. That said, I could see it being valuable for some. If there isn't any demand now, perhaps just make a github issue and let future collaborators know what they'd need to do to make those tests pass.

**Comment by merqlove** [comment]
Seems here wrong search, when we searching by map. For example:

```elixir
Repo.get_by(Some, map_field: %{})
```

It will search with `map_field: []`.
So result will be empty.

**Comment by merqlove** [comment]
I have added spec for this case:
https://github.com/cnsa/mongodb_ecto/commit/18dae110f9a49bc220fd435505a8e57252a695f7

**Comment by ankhers** [comment]
@merqlove I do not think that is an issue. I was able to insert and query properly based on map input.

```
iex(5)> Repo.insert(%Schema4{map1: %{"foo" => "bar"}, binary: "binary"})
{:ok,
 %Schema4{__meta__: #Ecto.Schema.Metadata<:loaded, "schema4">, binary: "binary",
  id: "589f3466b3acd935e72ce13e", map1: %{"foo" => "bar"}}}
[debug] QUERY OK db=35.4ms
INSERT coll="schema4" document=[binary: #BSON.Binary<62696e617279>, map1: %{"foo" => "bar"}, _id: #BSON.ObjectId<589f3466b3acd935e72ce13e>] []
iex(6)> Repo.all(Schema4)
[debug] QUERY OK db=0.2ms
FIND coll="schema4" query=[{"$query", []}, {"$orderby", %{}}] projection=%{_id: true, binary: true, map1: true} []
[%Schema4{__meta__: #Ecto.Schema.Metadata<:loaded, "schema4">, binary: "binary",
  id: "589f3466b3acd935e72ce13e", map1: %{"foo" => "bar"}}]
iex(7)> Repo.insert(%Schema4{binary: "binary2"})
[debug] QUERY OK db=0.4ms queue=0.1ms
INSERT coll="schema4" document=[binary: #BSON.Binary<62696e61727932>, map1: %{}, _id: #BSON.ObjectId<589f3487b3acd935e7d35197>] []
{:ok,
 %Schema4{__meta__: #Ecto.Schema.Metadata<:loaded, "schema4">,
  binary: "binary2", id: "589f3487b3acd935e7d35197", map1: %{}}}
iex(8)> Repo.all(from s in Schema4, where: s.map1 == ^%{})
[debug] QUERY OK db=0.2ms
FIND coll="schema4" query=[{"$query", [map1: %{}]}, {"$orderby", %{}}] projection=%{_id: true, binary: true, map1: true} []
[%Schema4{__meta__: #Ecto.Schema.Metadata<:loaded, "schema4">,
  binary: "binary2", id: "589f3487b3acd935e7d35197", map1: %{}}]
iex(9)> Repo.all(from s in Schema4, where: s.map1 == ^%{"foo" => "bar"})
[debug] QUERY OK db=0.2ms
FIND coll="schema4" query=[{"$query", [map1: %{"foo" => "bar"}]}, {"$orderby", %{}}] projection=%{_id: true, binary: true, map1: true} []
[%Schema4{__meta__: #Ecto.Schema.Metadata<:loaded, "schema4">, binary: "binary",
  id: "589f3466b3acd935e72ce13e", map1: %{"foo" => "bar"}}]
```

**Comment by ericmj** [comment]
@merqlove Can you show a failing test with `Repo.get_by`?

This is not mongodb behaviour:

```elixir
iex(1)> %{foo: %{}} |> BSON.encode |> BSON.decode
%{"foo" => %{}}
iex(2)> %{foo: []} |> BSON.encode |> BSON.decode
%{"foo" => []}
```

**Comment by ericmj** [comment]
It is possible that the adapter translates maps to keyword lists. If it does that it should not do it for empty maps.

**Comment by merqlove** [comment]
@ericmj @ankhers 
I have added 2 new specs.
First is failed, second with success.
https://github.com/cnsa/mongodb_ecto/commit/04853cbb457e953ce9f803bd7f0a429bfaf11024
Also here gist with illustration.
i did gist https://gist.github.com/merqlove/981c93faa52b751c64a538c147a2e25d

This is not critical moment, but better to have maps more predictable.

**Comment by ankhers** [comment]
Okay. When I showed this as working, I didn't realize but the project was using an older commit. This appears to be a regression. I will take a look at where this broke.

**Comment by ankhers** [comment]
I found the problem (It is the most recent commit). So I should be able to basically revert it and things should work as expected.

**Comment by merqlove** [comment]
@ankhers great! 
now i'm integrating our app into these changes, will write if found anything else.

`ex_machina` works ok with this upgrade.
`scrivener` paginator will not work at our side anymore because they use subquery. So `kerosene` :)

**Comment by michalmuskala** [comment]
Thank you @ankhers for working on this. 

I'm going to prepare for a release in https://github.com/michalmuskala/mongodb_ecto/pull/84.

**Comment by ankhers** [comment]
@merqlove Just so you know, I have fixed that issue. Though, going forward, you may want to switch to the official ecto-2 branch (that is where this fix is).

**Comment by merqlove** [comment]
Excellent, thanks!

**Comment by justmark** [comment]
@AlexKovalevych Any chance you could post some of your code to get the pipeline working?  I added it in, and it doesn't toss any errors, but doesn't appear to log any request to Mongo at all.

**Comment by merqlove** [comment]
@justmark do you have debug logs? because i have no problem with it (as it was before upgrade).

**Comment by AlexKovalevych** [comment]
@justmark if you mean aggregation pipeline, then it doesn't log those i think, since i use mongo driver directly, ecto has nothing to do with it. Aggregation example:

```elixir
    Mongo.aggregate(YourRepo.__mongo_pool__, collection_name, [%{"$match" => ..}, %{"$group" => ..}])
```

**Comment by justmark** [comment]
@AlexKovalevych Thanks - I've got:

```
cursor = Mongo.aggregate(Svr.Repo.__pool__,  "systems", pipeline )
```
but that results in an error:
```
no match of right hand side value: []
```
I also tried using your "__mongo_pool__" suggestion, but that also generated an error:

```
function Svr.Repo.__mongo_pool__/0 is undefined or private
```

**Comment by merqlove** [comment]
@justmark Seems you have wrong pipeline. 
I have no error in such query:
Mongo.aggregate(Repo.Pool, collection_name, [%{"$sample": [size: size]}], [])

**Comment by justmark** [comment]
@merqlove Hi, I saw in your query that you used "Repo.Pool".  I used this instead of what I had previously (Svr.Repo.__pool__) and your change worked.  

Thanks!

**Pull request merged**
